### ISSUE TITLE
Slight modifications in MPF layout

### ISSUE THREAD

**Issue by jogonmar** [jogonmar/MVBatch#10]
We should consider changing slightly the order of the objects and panels in the MPF layout to be consistent with other layouts in the software package. I propose that the panel for manual model building is located just below the information window, leaving the panel for data exploration below. This way we have a chronological order of the data modeling steps, which will be aligned with the spatial order in the GUI, i.e. CV map visualization -> model building (either automatic or manual) -> data and model exploration ->model selection for process monitoring. 
Just give it a thought. In the end it is your part, and if you consider that the original design must remain, just speak up. :-)
For the final design I propose, please have a look at the email I've sent you.

**Comment by josecamachop** [comment]
Agreed. Much better.
