### ISSUE TITLE
Conflic with PCA function of Matlab

### ISSUE THREAD

**Issue by jogonmar** [jogonmar/MVBatch#11]
I am using Matlab 2014a to test out the application, and it seems that MAthworks has changed the PCA function (princomp) since I get an error:

Error using pca (line 180)
Unrecognized input. Type: 'help pca'

Error in crossval3D_s (line 175)
                    p = pca(c_2D,'Centered',false,'NumComponents',pc);

Hence, we have here two options: either replace it with our own functions (SVD, NIPALS,...), or modify the input parameters of the function.

**Comment by josecamachop** [comment]
The problem is that we do not use the native "pca" function by Matlab, but pcamv in the MVBatch and pca_pp in the MEDA. I will fix it.

**Comment by josecamachop** [comment]
Solved
