### ISSUE TITLE
Download of MEDA toolbox when cloning path in local

### ISSUE THREAD

**Issue by jogonmar** [jogonmar/MVBatch#12]
I hereby confirm that when cloning the MVBatch path from Github, the MEDA toolbox is automatically  downloaded. Hence, we avoid any inconvenience to the final user.

**Comment by josecamachop** [comment]
The problem is that a standard user does not clone the git, but download the zip, and therefore they do not get the MEDA downloaded. We should comment this in the readme or install document

**Comment by jogonmar** [comment]
I will do it.
