### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by jogonmar** [jogonmar/MVBatch#16]
When pressing PCs button in the MPF GUI, the function var_pca is not found:
Undefined function 'var_pca' for input arguments of type 'double'.

When computing the CV maps, the function preprocess2D is not found:
Undefined function 'preprocess2D' for input arguments of type 'double'.
Error in cov_map (line 82)
xu = preprocess2D(unfold(x,Inf),1);

**Comment by josecamachop** [comment]
Both var_pca and preprocess2D are MEDA functions. This must be a problem of misconfiguration.

**Comment by jogonmar** [comment]
Yup. Updating the MEDA toolbox the problem is solved
