### ISSUE TITLE
Apply and Close options for GUIs

### ISSUE THREAD

**Issue by jogonmar** [jogonmar/MVBatch#23]
Give the option to close the GUI keeping the modeling step in memory.

**Comment by josecamachop** [comment]
I have finished this issue in the modeling GUI. However, I cannot make the GUI close. Please, have a look.

**Comment by jogonmar** [comment]
I have solved the issue you faced up with the Modeling user interface when closing and applying. Also I have updated the main interface to ensure that when we load a new data set, we change our current data set after variable and/or observation/batch screening, or we proceed with a new synchronization, the calibration structure is reset. In the previous version, after you modified the Modeling GUI to keep the empirical models when the user does not press the button "Apply" , it was not set up correctly.
