### ISSUE TITLE
Intro and About GUI

### ISSUE THREAD

**Issue by josecamachop** [jogonmar/MVBatch#3]
I recommend adjusting the Intro window to the graphic frame. I do not like the text in window 'About', and less still the use of a figure to show it.

**Comment by jogonmar** [comment]
Agree with you on removing the About window. Unfortunately, Matlab GUI designer does not provide good options to create a good About option. I understand that creating a figure to visualize such image is crappy.

In the next update, this will be removed.

**Comment by jogonmar** [comment]
I would suggest keeping the option File to open and save projects.
I hereby confirm that I have deleted the About option from the menu.
