### ISSUE TITLE
MEDA only available for VW model exploration 

### ISSUE THREAD

**Issue by jogonmar** [jogonmar/MVBatch#30]
Tried to explore the latent structures of derived models (batch-wise and multi-phase) with MEDA, but it seems that only VW models can be built and investigated with your toolbox. Please, confirm this.

Would make sense to call MEDA providing the different MV models, or the one selected by the user, and explore it with the visual tools. It does not make sense to constrain the user and the tool to fit VW models with MEDA.

**Comment by josecamachop** [comment]
Indeed, I think you can (otherwise, please give more information on how you got to the error)

You create a model, then select it in the pop-up list at the left-botton part of the gui (under 'Calibration Model') and select the phase you want to explore in 'Explore Data'. This should work.

**Comment by jogonmar** [comment]
This issue has been already solved and clarified in previous face-to-face meeting.
