### ISSUE TITLE
Windows opening

### ISSUE THREAD

**Issue by josecamachop** [jogonmar/MVBatch#7]
I would open the next window automatically instead that needing to push in the main window bottoms.

**Comment by jogonmar** [comment]
Agreed! However, we need to keep the main window bottoms to allow the users to go back to the data set and remove observations and variables based on the outcomes of the post-mortem monitoring. 
In addition, we should agree on the main steps of the modeling cycle for the software, just for the sake of consistency with what we mention in the book.

**Comment by josecamachop** [comment]
Yes, I think the steps in the software are ok. Looking at this problem now, what I would do is to change the text of the close buttom to "Close" in esch sub-interface, and only trigger the sub-intefaces from the main. This would leave functionality as it is, but just changing the labels of the buttons to "Close"
