### ISSUE TITLE
Functionalities from MEDA to MVBatch

### ISSUE THREAD

**Issue by josecamachop** [jogonmar/MVBatch#9]
Incorporate i) scatterplots for loadings, scores, ii) contribution plots and iii) cross-validation

**Comment by josecamachop** [comment]
Why and where this should be done?

**Comment by jogonmar** [comment]
1. Regarding the why, I believe that we agreed on adding the option of visualizing the scatterplots for loadings, and the Q plots (not the contribution plots). 
2. In the version of the software I uploaded to Dropbox and Github, I added the option of visualizing the contribution plots for all the models. In particular, I added the option to visualize the contribution to the D and Q statistics for a specific time point for all possible models (bw, vw, dynamic, multiphase), and the overall contribution, and the cumulated contribution per variable and per time when a BW is selected. This is done, so we can remove this from the to-do list. 
3. Concerning the “where”, scatterplots and Q matrices in the modeling window, and the cross-validation embedded in the routine for modeling building.
